<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.19041.0</TargetFrameworks>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>BarlinkTPV</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Enable XAML source generation for faster build times and improved performance.
		     This generates C# code from XAML at compile time instead of runtime inflation.
		     To disable, remove this line.
		     For individual files, you can override by setting Inflator metadata:
		       <MauiXaml Update="MyPage.xaml" Inflator="Default" /> (reverts to defaults: Runtime for Debug, XamlC for Release)
		       <MauiXaml Update="MyPage.xaml" Inflator="Runtime" /> (force runtime inflation) -->
		<MauiXamlInflator>SourceGen</MauiXamlInflator>

		<!-- Display name -->
		<ApplicationTitle>BarlinkTPV</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.barlinktpv</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>MSIX</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
		<MauiImage Include="Resources\Images\Products\Bocadillos\chivito.webp" />
		<MauiImage Include="Resources\Images\Products\Bocadillos\lomoqueso.png" />
		<MauiImage Include="Resources\Images\Products\Bocadillos\serranito.png" />
		<MauiImage Include="Resources\Images\Products\Cafes\americano.png" />
		<MauiImage Include="Resources\Images\Products\Cafes\bombon.png" />
		<MauiImage Include="Resources\Images\Products\Cafes\cafeleche.webp" />
		<MauiImage Include="Resources\Images\Products\Cafes\expresso.png" />
		<MauiImage Include="Resources\Images\Products\Carnes\chuleton.png" />
		<MauiImage Include="Resources\Images\Products\Carnes\entrecot.webp" />
		<MauiImage Include="Resources\Images\Products\Carnes\wagyu.webp" />
		<MauiImage Include="Resources\Images\Products\Cervezas\cania.png" />
		<MauiImage Include="Resources\Images\Products\Cervezas\jarralitro.png" />
		<MauiImage Include="Resources\Images\Products\Cervezas\tercio.png" />
		<MauiImage Include="Resources\Images\Products\Cubatas\barcelo.jpg" />
		<MauiImage Include="Resources\Images\Products\Cubatas\beefeater.webp" />
		<MauiImage Include="Resources\Images\Products\Cubatas\jb.png" />
		<MauiImage Include="Resources\Images\Products\Cubatas\larios.webp" />
		<MauiImage Include="Resources\Images\Products\Desayunos\croissant.png" />
		<MauiImage Include="Resources\Images\Products\Desayunos\napolitana.png" />
		<MauiImage Include="Resources\Images\Products\Desayunos\zumomelocoton.png" />
		<MauiImage Include="Resources\Images\Products\Desayunos\zumonaranja.png" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Images\Categories\bocadillos.png" />
	  <None Remove="Resources\Images\Categories\bocadillosb.png" />
	  <None Remove="Resources\Images\Categories\cafes.png" />
	  <None Remove="Resources\Images\Categories\cafesb.png" />
	  <None Remove="Resources\Images\Categories\carnes.png" />
	  <None Remove="Resources\Images\Categories\carnesb.png" />
	  <None Remove="Resources\Images\Categories\cervezas.png" />
	  <None Remove="Resources\Images\Categories\cervezasb.png" />
	  <None Remove="Resources\Images\Categories\cubatas.png" />
	  <None Remove="Resources\Images\Categories\cubatasb.png" />
	  <None Remove="Resources\Images\Categories\desayunos.png" />
	  <None Remove="Resources\Images\Categories\desayunosb.png" />
	  <None Remove="Resources\Images\Categories\licores.png" />
	  <None Remove="Resources\Images\Categories\licoresb.png" />
	  <None Remove="Resources\Images\Categories\raciones.png" />
	  <None Remove="Resources\Images\Categories\racionesb.png" />
	  <None Remove="Resources\Images\Categories\refrescosb.png" />
	  <None Remove="Resources\Images\Categories\vinos.png" />
	  <None Remove="Resources\Images\Categories\vinosb.png" />
	  <None Remove="Resources\Images\Products\agua.bmp" />
	  <None Remove="Resources\Images\Products\bjamon.bmp" />
	  <None Remove="Resources\Images\Products\blomo.bmp" />
	  <None Remove="Resources\Images\Products\Bocadillos\chivito.webp" />
	  <None Remove="Resources\Images\Products\Bocadillos\lomoqueso.png" />
	  <None Remove="Resources\Images\Products\Bocadillos\serranito.png" />
	  <None Remove="Resources\Images\Products\cafe.bmp" />
	  <None Remove="Resources\Images\Products\Cafes\americano.png" />
	  <None Remove="Resources\Images\Products\Cafes\bombon.png" />
	  <None Remove="Resources\Images\Products\Cafes\cafeleche.webp" />
	  <None Remove="Resources\Images\Products\Cafes\expresso.png" />
	  <None Remove="Resources\Images\Products\cania.bmp" />
	  <None Remove="Resources\Images\Products\cardhu.bmp" />
	  <None Remove="Resources\Images\Products\Carnes\chuleton.png" />
	  <None Remove="Resources\Images\Products\Carnes\entrecot.webp" />
	  <None Remove="Resources\Images\Products\Carnes\wagyu.webp" />
	  <None Remove="Resources\Images\Products\Cervezas\cania.png" />
	  <None Remove="Resources\Images\Products\Cervezas\jarralitro.png" />
	  <None Remove="Resources\Images\Products\Cervezas\tercio.png" />
	  <None Remove="Resources\Images\Products\cocacola.bmp" />
	  <None Remove="Resources\Images\Products\colacao.bmp" />
	  <None Remove="Resources\Images\Products\copablanco.bmp" />
	  <None Remove="Resources\Images\Products\copatinto.bmp" />
	  <None Remove="Resources\Images\Products\croissant.bmp" />
	  <None Remove="Resources\Images\Products\Cubatas\barcelo.jpg" />
	  <None Remove="Resources\Images\Products\Cubatas\beefeater.webp" />
	  <None Remove="Resources\Images\Products\Cubatas\jb.png" />
	  <None Remove="Resources\Images\Products\Cubatas\larios.webp" />
	  <None Remove="Resources\Images\Products\Desayunos\croissant.png" />
	  <None Remove="Resources\Images\Products\Desayunos\napolitana.png" />
	  <None Remove="Resources\Images\Products\Desayunos\zumomelocoton.png" />
	  <None Remove="Resources\Images\Products\Desayunos\zumonaranja.png" />
	  <None Remove="Resources\Images\Products\fantalimon.bmp" />
	  <None Remove="Resources\Images\Products\fantanaranja.bmp" />
	  <None Remove="Resources\Images\Products\hierbas.bmp" />
	  <None Remove="Resources\Images\Products\jarralitro.bmp" />
	  <None Remove="Resources\Images\Products\larios.bmp" />
	  <None Remove="Resources\Images\Products\Licores\licorhierbas.png" />
	  <None Remove="Resources\Images\Products\Licores\orujo.png" />
	  <None Remove="Resources\Images\Products\orujo.bmp" />
	  <None Remove="Resources\Images\Products\Raciones\patatasbravas.png" />
	  <None Remove="Resources\Images\Products\Raciones\rabofrito.png" />
	  <None Remove="Resources\Images\Products\rcalamares.bmp" />
	  <None Remove="Resources\Images\Products\Refrescos\cocacola.png" />
	  <None Remove="Resources\Images\Products\Refrescos\fantalimon.png" />
	  <None Remove="Resources\Images\Products\Refrescos\fantanaranja.png" />
	  <None Remove="Resources\Images\Products\sidragaitero.bmp" />
	  <None Remove="Resources\Images\Products\surtidoibericos.bmp" />
	  <None Remove="Resources\Images\Products\tostadaaceite.bmp" />
	  <None Remove="Resources\Images\Products\vinoblanco.bmp" />
	  <None Remove="Resources\Images\Products\Vinos\botvinoblanco.png" />
	  <None Remove="Resources\Images\Products\Vinos\botvinotinto.png" />
	  <None Remove="Resources\Images\Products\Vinos\copablanco.png" />
	  <None Remove="Resources\Images\Products\Vinos\copatinto.webp" />
	  <None Remove="Resources\Images\Products\vinotinto.bmp" />
	  <None Remove="Resources\Images\Products\zumonaranja.bmp" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Include="Resources\Images\Categories\bocadillos.png" />
	  <MauiImage Include="Resources\Images\Categories\cafes.png" />
	  <MauiImage Include="Resources\Images\Categories\carnes.png" />
	  <MauiImage Include="Resources\Images\Categories\cervezas.png" />
	  <MauiImage Include="Resources\Images\Categories\cubatas.png" />
	  <MauiImage Include="Resources\Images\Categories\desayunos.png" />
	  <MauiImage Include="Resources\Images\Categories\licores.png" />
	  <MauiImage Include="Resources\Images\Categories\raciones.png" />
	  <MauiImage Include="Resources\Images\Categories\refrescos.png" />
	  <MauiImage Include="Resources\Images\Categories\vinos.png" />
	  <MauiImage Include="Resources\Images\Products\Raciones\patatasbravas.png" />
	  <MauiImage Include="Resources\Images\Products\Raciones\rabofrito.png" />
	  <MauiImage Include="Resources\Images\Products\Raciones\rcalamares.bmp" />
	  <MauiImage Include="Resources\Images\Products\Raciones\surtidoibericos.bmp" />
	  <MauiImage Include="Resources\Images\Products\Refrescos\agua.png" />
	  <MauiImage Include="Resources\Images\Products\Refrescos\cocacola.png" />
	  <MauiImage Include="Resources\Images\Products\Refrescos\fantalimon.png" />
	  <MauiImage Include="Resources\Images\Products\Refrescos\fantanaranja.png" />
	  <MauiImage Include="Resources\Images\Products\Vinos\botvinoblanco.png" />
	  <MauiImage Include="Resources\Images\Products\Vinos\botvinotinto.png" />
	  <MauiImage Include="Resources\Images\Products\Vinos\copablanco.png" />
	  <MauiImage Include="Resources\Images\Products\Vinos\copatinto.webp" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="14.1.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.60" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.8" />
		<PackageReference Include="Syncfusion.Maui.Charts" Version="33.2.6" />
		<PackageReference Include="Syncfusion.Maui.Core" Version="33.2.6" />
		<PackageReference Include="Syncfusion.Maui.DataGrid" Version="33.2.6" />
		<PackageReference Include="Syncfusion.Maui.Toolkit" Version="1.0.9" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Navigation\InitialNavigation.xaml.cs">
	    <DependentUpon>InitialNavigation.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Navigation\AdminNavigation.xaml.cs">
	    <DependentUpon>AdminNavigation.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Popups\ModifyTicketLinePopup.xaml.cs">
	    <DependentUpon>ModifyTicketLinePopup.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\HomeAdminView.xaml.cs">
	    <DependentUpon>HomeAdminView.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Navigation\InitialNavigation.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Navigation\AdminNavigation.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Navigation\UserNavigation.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Popups\CreateUserPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Popups\ModifyTicketLinePopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Popups\ModifyUserPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Popups\WorkerRegPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Languages\English.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Languages\Spanish.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\DarkTheme.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\LightTheme.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\MainTheme.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HomeAdminView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\HomeView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\LoginView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\OrderView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\PosView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SalesReportsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\SettingsView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\UsersManagementView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Include="Resources\Images\Products\Licores\licorhierbas.png" />
	  <MauiImage Include="Resources\Images\Products\Licores\orujo.png" />
	</ItemGroup>

</Project>
